image: alpine/edge
packages:
- calibre
- hut
- mdbook
- rust
oauth: pages.sr.ht/PAGES:RW
sources:
- https://git.sr.ht/~sircmpwn/wayland-book
artifacts:
- wayland-book/book/The-Wayland-Book.epub
tasks:
- build: |
    cd wayland-book
    mdbook build
- epub: |
    cd wayland-book
    ebook-convert book/print.html book/The-Wayland-Book.epub
- deploy: |
    cd wayland-book
    hut pages publish -d wayland-book.com ./book
